version: "3"
services:
  node:
    #image: node:latest
    build: ./docker/engine
    expose:
        - "5000"
    ports:
        - "5000:5000"

    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    command: "serve -s /home/node/app/dist"
    volumes:
        - ./dev:/home/node/app
    
    labels:
        - "traefik.docker.network=traefik"
        - "traefik.backend=chaussendeX2"
        - "traefik.frontend.rule=Host:chaussendeX2.netime.net"
        - "traefik.port=80"
    networks:
        - traefik

networks:
  traefik:
    external:
      name: traefik_webgateway